source 'https://rubygems.org'

group :development do
  gem "vagrant", git: "https://github.com/mitchellh/vagrant.git"
  gem "rake", ">= 12.3.3"
end

group :plugins do
  # gem "vagrant-vbguest", git: "https://github.com/dotless-de/vagrant-vbguest.git"
  gem "vagrant-vbguest", path: "../.."
  gem "vagrant-vbguest-unikorn", path: "."
end
